/**
 * Knowledge Preview (FASE 06 §5) — simulations only. Nothing here is served,
 * persisted or generated by AI: every output is a pure projection.
 */
import { Card } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Eye } from "lucide-react";
import {
  DERIVATION_KINDS,
  DERIVATION_LABEL,
  derive,
} from "../../../domain/factory/derivations";
import type { KnowledgeDraft } from "../../../domain/factory/KnowledgeDraft";

export const PreviewPanel = ({ draft }: { draft: KnowledgeDraft }) => (
  <Card className="p-5">
    <div className="flex items-center gap-2">
      <Eye className="h-4 w-4 text-primary" />
      <h3 className="font-semibold text-foreground">Knowledge Preview</h3>
    </div>
    <p className="mt-1 text-xs text-muted-foreground">
      Simulações determinísticas do objeto. Nada é gerado por IA nem publicado.
    </p>

    <Tabs defaultValue={DERIVATION_KINDS[0]} className="mt-4">
      <TabsList className="flex h-auto flex-wrap justify-start gap-1 bg-muted/60">
        {DERIVATION_KINDS.map((k) => (
          <TabsTrigger key={k} value={k} className="text-xs">
            {DERIVATION_LABEL[k]}
          </TabsTrigger>
        ))}
      </TabsList>

      {DERIVATION_KINDS.map((k) => (
        <TabsContent key={k} value={k}>
          <pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded-lg bg-muted/50 p-4 text-xs leading-relaxed text-foreground">
            {derive(draft, k)}
          </pre>
        </TabsContent>
      ))}
    </Tabs>
  </Card>
);